#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0
#define IGNORE_MOD_TAP_INTERRUPT


// #define RETRO_SHIFT
#define RETRO_SHIFT 400
// #define AUTO_SHIFT_TIMEOUT  200
// #define NO_AUTO_SHIFT_SPECIAL
// #define NO_AUTO_SHIFT_NUMERIC
